### ISSUE TITLE
Add unique id to sections

### ISSUE THREAD

**Issue by galacticglum** [sqrl-planner/gator#35]
For [issue #26 in sqrl-client](https://github.com/sqrl-planner/sqrl-client/issues/26), we'll need to a way to refer to sections uniquely (within a course).

We can do this by constructing an id according the format `<section_type>-<id>`.  NOTE: as the Section model is embedded in the Course document, these are ids in the sense that they are unique within the course document.

**Comment by joelebutler** [comment]
Could I get some clarification on how this is different from the code method in the Section class?

https://github.com/sqrl-planner/gator/blob/75faa95475084db0cb59c5f5a31d966fc80d5037/gator/models/timetable.py#L114-L119

**Comment by galacticglum** [comment]
I think that's the same thing. Looks like I did this a while back - probably in anticipation for something like this. I'll close the issue for now. Thanks for pointing it out.
